name: global_pos
description: A professional Point of Sale system
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  fl_chart: ^0.65.0
  intl: ^0.18.1
  pdf: ^3.10.7
  printing: ^5.11.1
  path_provider: ^2.1.1
  file_picker: ^8.0.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
